In [1]:

 # Cellule 1 - Imports et configuration
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
import joblib
import os
import pandas as pd
import numpy as np
import logging

# Configuration du logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Chemins des modèles
MODEL_DIR = "models"
MODEL_PATH = os.path.join(MODEL_DIR, "isolation_forest_v1.joblib")
SCALER_PATH = os.path.join(MODEL_DIR, "scaler_v1.joblib")

# Création du dossier models si inexistant
os.makedirs(MODEL_DIR, exist_ok=True)

In [ ]:
# Assurez-vous que geopy est installé dans le venv utilisé par le notebook
import sys
import subprocess

try:
    import geopy
except ModuleNotFoundError:
    print("geopy non trouvé, installation en cours...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "geopy"])
    print("Installation terminée !")

# Import des modules geopy
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
from geopy.exc import GeocoderTimedOut, GeocoderServiceError

print("geopy est prêt ✅")

geopy non trouvé, installation en cours...
Installation terminée !
geopy est prêt ✅

In [ ]:
# Cellule 1 - Imports et configuration from sklearn.ensemble import IsolationForest from sklearn.preprocessing import StandardScaler import joblib import os import pandas as pd import numpy as np import logging # Configuration du logging logging.basicConfig(level=logging.INFO) logger = logging.getLogger(__name__) # Chemins des modèles MODEL_DIR = "models" MODEL_PATH = os.path.join(MODEL_DIR, "isolation_forest_v1.joblib") SCALER_PATH = os.path.join(MODEL_DIR, "scaler_v1.joblib") # Création du dossier models si inexistant os.makedirs(MODEL_DIR, exist_ok=True) # Données des codes postaux marocains par ville MOROCCAN_POSTAL_CODES = { 'Casablanca': ['20000', '20200', '20250', '20300', '20340'], 'Rabat': ['10000', '10100', '10170'], 'Marrakech': ['40000', '40020', '40060', '40100'], 'Tanger': ['90000', '90010', '90050'], 'Fès': ['30000', '30050', '30100'], 'Meknès': ['50000', '50050'], 'Agadir': ['80000', '80010', '80050'], 'Oujda': ['60000', '60050'], 'Tétouan': ['93000', '93010'], 'Safi': ['46000'], 'Kénitra': ['14000', '14050'], 'El Jadida': ['24000'], 'Nador': ['62000'], 'Settat': ['26000'], 'Larache': ['92000'], 'Khémisset': ['15000'], 'Taza': ['35000'], 'Béni Mellal': ['23000'], 'Errachidia': ['52000'], 'Al Hoceïma': ['32000'] } # Dictionnaire local : ville -> (lat, lon, postcode) city_data = { 'Casablanca': (33.5731, -7.5898, '20000'), 'Rabat': (34.0209, -6.8416, '10000'), 'Marrakech': (31.6295, -7.9811, '40000'), 'Tanger': (35.7595, -5.8339, '90000'), 'Fès': (34.0331, -5.0003, '30000'), 'Meknès': (33.8950, -5.5547, '50000'), 'Agadir': (30.4278, -9.5981, '80000'), 'Oujda': (34.6810, -1.9002, '60000') } # 1. Génération des données "normales" avec des montants réalistes num_normal = 500 np.random.seed(42) # Distribution réaliste des montants pour transactions normales low_amounts = np.random.uniform(100, 5000, int(num_normal * 0.6)) # 60% petites transactions medium_amounts = np.random.uniform(5000, 50000, int(num_normal * 0.3)) # 30% transactions moyennes high_amounts = np.random.uniform(50000, 200000, int(num_normal * 0.1)) # 10% grosses transactions all_amounts = np.concatenate([low_amounts, medium_amounts, high_amounts]) np.random.shuffle(all_amounts) data_normal = pd.DataFrame({ 'is_anomaly': [0] * num_normal, 'is_international': [False] * num_normal, 'intrbk_sttlm_amt': all_amounts, 'distance_km': np.random.randint(1, 800, num_normal), 'debtor_country': ['MA'] * num_normal, 'creditor_country': ['MA'] * num_normal, 'debtor_city': np.random.choice(list(city_data.keys()), num_normal), 'creditor_city': np.random.choice(list(city_data.keys()), num_normal), 'debtor_name': np.random.choice(['ATTIJARIWAFA BANK', 'BANQUE POPULAIRE', 'BMCE BANK', 'CREDIT DU MAROC', 'SOCIETE GENERALE MAROC'], num_normal), 'creditor_name': np.random.choice(['ATTIJARIWAFA BANK', 'BANQUE POPULAIRE', 'BMCE BANK', 'CREDIT DU MAROC', 'SOCIETE GENERALE MAROC'], num_normal), }) # Ajouter les coordonnées et codes postaux for role in ['debtor', 'creditor']: data_normal[f'{role}_lat'] = data_normal[f'{role}_city'].map(lambda x: city_data[x][0]) data_normal[f'{role}_lon'] = data_normal[f'{role}_city'].map(lambda x: city_data[x][1]) data_normal[f'{role}_postcode'] = data_normal[f'{role}_city'].map(lambda x: city_data[x][2]) data_normal['intrbk_sttlm_amt_log'] = np.log1p(data_normal['intrbk_sttlm_amt']) # 2. Création de transactions "anormales" avec différents scénarios abnormal_transactions = pd.DataFrame([ # Transaction très élevée { 'is_anomaly': 1, 'is_international': False, 'intrbk_sttlm_amt': 5000000.00, # 5M MAD 'distance_km': 10, # Très courte distance pour un gros montant 'debtor_country': 'MA', 'creditor_country': 'MA', 'debtor_city': 'Casablanca', 'creditor_city': 'Casablanca', 'debtor_name': 'ENTREPRISE A', 'creditor_name': 'ENTREPRISE B', 'debtor_lat': city_data['Casablanca'][0], 'debtor_lon': city_data['Casablanca'][1], 'debtor_postcode': city_data['Casablanca'][2], 'creditor_lat': city_data['Casablanca'][0], 'creditor_lon': city_data['Casablanca'][1], 'creditor_postcode': city_data['Casablanca'][2], 'intrbk_sttlm_amt_log': np.log1p(5000000.00) }, # Transaction suspecte avec incohérence de code postal { 'is_anomaly': 1, 'is_international': False, 'intrbk_sttlm_amt': 12000.00, 'distance_km': 86.25, 'debtor_country': 'MA', 'creditor_country': 'MA', 'debtor_city': 'Casablanca', 'creditor_city': 'Casablanca', 'debtor_name': 'ENTREPRISE B', 'creditor_name': 'FOURNISSEUR LOCAL', 'debtor_lat': city_data['Casablanca'][0], 'debtor_lon': city_data['Casablanca'][1], 'debtor_postcode': '10000', # Code postal de Rabat pour Casablanca 'creditor_lat': city_data['Casablanca'][0], 'creditor_lon': city_data['Casablanca'][1], 'creditor_postcode': city_data['Casablanca'][2], 'intrbk_sttlm_amt_log': np.log1p(12000.00) }, # Transaction internationale suspecte { 'is_anomaly': 1, 'is_international': True, 'intrbk_sttlm_amt': 250000.00, 'distance_km': 2000, # Longue distance 'debtor_country': 'MA', 'creditor_country': 'FR', 'debtor_city': 'Casablanca', 'creditor_city': 'Paris', 'debtor_name': 'PARTICULIER', 'creditor_name': 'SOCIETE ETRANGERE', 'debtor_lat': city_data['Casablanca'][0], 'debtor_lon': city_data['Casablanca'][1], 'debtor_postcode': city_data['Casablanca'][2], 'creditor_lat': 48.8566, 'creditor_lon': 2.3522, 'creditor_postcode': '75000', 'intrbk_sttlm_amt_log': np.log1p(250000.00) } ]) # 3. Combinaison des deux DataFrames data_train = pd.concat([data_normal, abnormal_transactions], ignore_index=True) # 4. Ajout de features supplémentaires pour améliorer la détection data_train['amount_to_distance_ratio'] = data_train['intrbk_sttlm_amt'] / (data_train['distance_km'] + 1) data_train['is_same_city'] = (data_train['debtor_city'] == data_train['creditor_city']).astype(int) data_train['amount_category'] = pd.cut(data_train['intrbk_sttlm_amt'], bins=[0, 1000, 10000, 50000, 200000, np.inf], labels=['très_faible', 'faible', 'moyen', 'élevé', 'très_élevé']) print(f"Dataset d'entraînement créé avec {len(data_train)} transactions") print(f"Nombre d'anomalies: {len(abnormal_transactions)}") print(f"Nombre de transactions normales: {len(data_normal)}")

In [42]:
from app.ml_model import FraudModel
from sklearn.preprocessing import StandardScaler
import joblib
import os

fraud_model = FraudModel()

# Vérification et création du scaler si nécessaire
if fraud_model.scaler is None:
    print("Création d'un nouveau scaler...")
    fraud_model.scaler = StandardScaler()
    # Utiliser data_train au lieu de train_df
    features = data_train[fraud_model.expected_features]
    fraud_model.scaler.fit(features)
    joblib.dump(fraud_model.scaler, SCALER_PATH)
    print(f"Scaler enregistré à {SCALER_PATH}")

# Entraînement du modèle

if fraud_model.model is None or not hasattr(fraud_model.model, 'estimators_'):
    print("Entraînement du modèle...")
    features = data_train[fraud_model.expected_features]
    
    # ✅ ne pas convertir en numpy, garder DataFrame
    scaled_features = fraud_model.scaler.transform(features) if fraud_model.scaler else features
    
    fraud_model.model = IsolationForest(contamination=0.01, random_state=42)
    fraud_model.model.fit(scaled_features)
    joblib.dump(fraud_model.model, MODEL_PATH)
    print(f"Modèle enregistré à {MODEL_PATH}")


# Vérification finale
print("\nÉtat des composants:")
print(f"- Scaler chargé: {fraud_model.scaler is not None}")
print(f"- Modèle chargé: {fraud_model.model is not None}")
if fraud_model.model is not None:
    print(f"- Modèle entraîné: {hasattr(fraud_model.model, 'estimators_')}")

État des composants:
- Scaler chargé: True
- Modèle chargé: True
- Modèle entraîné: True

In [43]:
def prepare_for_detection(df, model):
    """Prépare les données pour la détection d'anomalies"""
    df = model.standardize_amount_column(df)
    
    # Vérification des features
    missing = [f for f in model.expected_features if f not in df.columns]
    if missing:
        available = [c for c in df.columns if c in model.expected_features]
        raise ValueError(
            f"Features manquantes: {missing}\n"
            f"Features disponibles: {available}\n"
            f"Features attendues: {model.expected_features}"
        )
    return df

try:
    # Préparation des données - utiliser data_train
    prepared_data = prepare_for_detection(data_train.copy(), fraud_model)
    
    # Détection des anomalies
    results = fraud_model.detect_anomalies(prepared_data)
    print("\n✅ Détection terminée avec succès")
    display(results.head())
    
except Exception as e:
    print("\n❌ Erreur:", str(e))
    print("Détails de débogage:")
    print(f"- Scaler disponible: {fraud_model.scaler is not None}")
    print(f"- Modèle disponible: {fraud_model.model is not None}")
    if fraud_model.model:
        print(f"- Modèle entraîné: {hasattr(fraud_model.model, 'estimators_')}")

c:\Users\Bellamine Kenza\Desktop\fraud_new\app\ml_model.py:117: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df.loc[:, 'is_international'] = (df['debtor_country'] != df['creditor_country']).astype(int)
c:\Users\Bellamine Kenza\Desktop\fraud_new\app\ml_model.py:131: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, 'is_international'] = (df['debtor_country'] != df['creditor_country'])

Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000292A02C3530>, 'Connection to nominatim.openstreetmap.org timed out. (connect timeout=1)')': /search?q=Marrakech%2C+MA&format=json&limit=1

Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=33.5945144&lon=-7.6200284&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Casablanca: 20032
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Tanger%2C+MA&format=json&limit=1

Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Casablanca%2C+MA&format=json&limit=1

Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Rabat%2C+MA&format=json&limit=1

Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Tanger%2C+MA&format=json&limit=1

Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=35.7696302&lon=-5.8033522&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Tanger: 90023
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Rabat%2C+MA&format=json&limit=1

Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=34.0218454&lon=-6.8408929&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Rabat: 10115
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=33.5945144&lon=-7.6200284&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Casablanca: 20032

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Rabat%2C+MA&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Rabat%2C+MA&format=json&limit=1

Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Tanger%2C+MA&format=json&limit=1

Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Marrakech: 40034
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Marrakech%2C+MA&format=json&limit=1

Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Marrakech%2C+MA&format=json&limit=1

Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Tanger%2C+MA&format=json&limit=1

Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Marrakech: 40034
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=33.5945144&lon=-7.6200284&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Casablanca: 20032
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=35.7696302&lon=-5.8033522&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Tanger: 90023
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Marrakech: 40034
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Marrakech%2C+MA&format=json&limit=1

Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=34.0218454&lon=-6.8408929&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Rabat: 10115
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Marrakech: 40034
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Rabat%2C+MA&format=json&limit=1

Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=34.0218454&lon=-6.8408929&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Rabat: 10115
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=33.5945144&lon=-7.6200284&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Casablanca: 20032
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Marrakech: 40034
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Marrakech: 40034
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=33.5945144&lon=-7.6200284&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Casablanca: 20032
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Tanger%2C+MA&format=json&limit=1

Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=35.7696302&lon=-5.8033522&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Tanger: 90023

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Marrakech%2C+MA&format=json&limit=1

Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Marrakech: 40034
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Rabat%2C+MA&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000292A02BD5E0>, 'Connection to nominatim.openstreetmap.org timed out. (connect timeout=1)')': /search?q=Rabat%2C+MA&format=json&limit=1

Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=34.0218454&lon=-6.8408929&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Rabat: 10115
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=33.5945144&lon=-7.6200284&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Casablanca: 20032
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=34.0218454&lon=-6.8408929&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Rabat: 10115
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=35.7696302&lon=-5.8033522&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Tanger: 90023
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Casablanca%2C+MA&format=json&limit=1

Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=35.7696302&lon=-5.8033522&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Tanger: 90023
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=34.0218454&lon=-6.8408929&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Rabat: 10115
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=35.7696302&lon=-5.8033522&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Tanger: 90023
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Marrakech: 40034
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=35.7696302&lon=-5.8033522&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Tanger: 90023
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=33.5945144&lon=-7.6200284&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Casablanca: 20032
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Marrakech: 40034
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=35.7696302&lon=-5.8033522&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Tanger: 90023
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=33.5945144&lon=-7.6200284&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Casablanca: 20032
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=34.0218454&lon=-6.8408929&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Rabat: 10115
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Rabat%2C+MA&format=json&limit=1

Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=34.0218454&lon=-6.8408929&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Rabat: 10115
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=33.5945144&lon=-7.6200284&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Casablanca: 20032
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Tanger, Code postal attendu : 90023
Débiteur: Ville : Marrakech, Code postal attendu : 40034
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Rabat, Code postal attendu : 10115
Débiteur: Ville : Casablanca, Code postal attendu : 20032
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Rabat%2C+MA&format=json&limit=1

Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Tanger%2C+MA&format=json&limit=1

Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=35.7696302&lon=-5.8033522&format=json&accept-language=en&addressdetails=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000292A02B4620>, 'Connection to nominatim.openstreetmap.org timed out. (connect timeout=1)')': /reverse?lat=35.7696302&lon=-5.8033522&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Tanger: 90023

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Rabat%2C+MA&format=json&limit=1

Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=33.5945144&lon=-7.6200284&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Casablanca: 20032

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Rabat%2C+MA&format=json&limit=1

Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Marrakech%2C+MA&format=json&limit=1

Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Rabat%2C+MA&format=json&limit=1

Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=34.0218454&lon=-6.8408929&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Rabat: 10115
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Marrakech: 40034
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Marrakech: 40034
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Marrakech: 40034
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Marrakech: 40034

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Rabat%2C+MA&format=json&limit=1

Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Tanger%2C+MA&format=json&limit=1

Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=35.7696302&lon=-5.8033522&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Tanger: 90023
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=34.0218454&lon=-6.8408929&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Rabat: 10115
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Casablanca%2C+MA&format=json&limit=1

Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=35.7696302&lon=-5.8033522&format=json&accept-language=en&addressdetails=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=35.7696302&lon=-5.8033522&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Tanger: 90023
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=33.5945144&lon=-7.6200284&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Casablanca: 20032
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=35.7696302&lon=-5.8033522&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Tanger: 90023
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=35.7696302&lon=-5.8033522&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Tanger: 90023
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Marrakech: 40034
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Marrakech: 40034
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Marrakech: 40034
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=35.7696302&lon=-5.8033522&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Tanger: 90023
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Marrakech: 40034
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=34.0218454&lon=-6.8408929&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Rabat: 10115
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Rabat%2C+MA&format=json&limit=1

Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Tanger%2C+MA&format=json&limit=1

Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Tanger%2C+MA&format=json&limit=1

Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Rabat%2C+MA&format=json&limit=1

Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Rabat%2C+MA&format=json&limit=1

Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=34.0218454&lon=-6.8408929&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Rabat: 10115
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Tanger%2C+MA&format=json&limit=1

Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Tanger%2C+MA&format=json&limit=1

Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Tanger%2C+MA&format=json&limit=1

Ville: Tanger, Pays: MA -> Coordonnées: 35.7696302, -5.8033522
Code postal trouvé pour Tanger: 90023
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=31.6258257&lon=-7.9891608&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Marrakech: 40034
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Marrakech%2C+MA&format=json&limit=1

Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=34.0218454&lon=-6.8408929&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Rabat: 10115
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=33.5945144&lon=-7.6200284&format=json&accept-language=en&addressdetails=1

Code postal trouvé pour Casablanca: 20032
Ville: Marrakech, Pays: MA -> Coordonnées: 31.6258257, -7.9891608
Code postal trouvé pour Marrakech: 40034
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Rabat, Pays: MA -> Coordonnées: 34.0218454, -6.8408929
Code postal trouvé pour Rabat: 10115
Ville: Casablanca, Pays: MA -> Coordonnées: 33.5945144, -7.6200284
Code postal trouvé pour Casablanca: 20032
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Tanger, Code postal attendu : 90023
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Casablanca, Code postal attendu : 20032
Créancier: Ville : Marrakech, Code postal attendu : 40034
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Rabat, Code postal attendu : 10115
Créancier: Ville : Casablanca, Code postal attendu : 20032

c:\Users\Bellamine Kenza\Desktop\fraud_new\venv\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but IsolationForest was fitted without feature names
  warnings.warn(
c:\Users\Bellamine Kenza\Desktop\fraud_new\venv\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but IsolationForest was fitted without feature names
  warnings.warn(
c:\Users\Bellamine Kenza\Desktop\fraud_new\app\ml_model.py:223: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ True False False  True False False False False False  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, 'is_anomaly'] = (df['combined_score'] > 0.5) | (df['rule_based_anomaly']).astype(int)

✅ Détection terminée avec succès

,is_anomaly,is_international,intrbk_sttlm_amt,distance_km,debtor_country,creditor_country,debtor_city,creditor_city,debtor_name,creditor_name,...,postal_incoherence_debtor,expected_postcode_creditor,postal_incoherence_creditor,bank_country_mismatch,ai_score,ai_anomaly,ai_score_normalized,rule_score_norm,ai_score_norm,combined_score
0,True,False,19563.0,79.0,MA,MA,Rabat,Casablanca,ATTIJARIWAFA BANK,BMCE BANK,...,True,20032,True,False,0.108155,0,0.888743,0.571429,0.445922,0.508676
1,False,False,83312.0,533.0,MA,MA,Tanger,Marrakech,ATTIJARIWAFA BANK,BANQUE POPULAIRE,...,True,40034,True,False,0.252234,0,0.061442,0.285714,0.373883,0.329799
2,False,False,180329.0,137.0,MA,MA,Marrakech,Rabat,BMCE BANK,ATTIJARIWAFA BANK,...,True,10115,True,False,0.188970,0,0.424704,0.285714,0.405515,0.345615
3,True,False,198144.0,480.0,MA,MA,Tanger,Tanger,BANQUE POPULAIRE,BANQUE POPULAIRE,...,True,90023,True,False,0.190459,0,0.416155,0.571429,0.404771,0.488100
4,False,False,17165.0,573.0,MA,MA,Casablanca,Casablanca,ATTIJARIWAFA BANK,BANQUE POPULAIRE,...,True,20032,True,False,0.088779,0,1.000000,0.285714,0.455610,0.370662

In [44]:
anomalies = results[results['is_anomaly'] == 1]
print(f"\nNombre d'anomalies détectées : {len(anomalies)}")

# Afficher un tableau complet avec les colonnes importantes
display(anomalies[['intrbk_sttlm_amt', 'debtor_country', 
                  'creditor_country', 'is_international', 'rule_based_score', 
                  'ai_score', 'combined_score']])

Nombre d'anomalies détectées : 3

,intrbk_sttlm_amt,debtor_country,creditor_country,is_international,rule_based_score,ai_score,combined_score
0,19563.0,MA,MA,False,2.0,0.108155,0.508676
3,198144.0,MA,MA,False,2.0,0.190459,0.488100
9,2647.0,MA,MA,False,2.0,0.088779,0.513519

In [ ]:
# Vérification des caractéristiques
print("Features attendues par le modèle:", fraud_model.expected_features)
print("\nFeatures disponibles dans data_train:")
print([col for col in data_train.columns if col in fraud_model.expected_features])

# Vérifier si les features nécessaires sont présentes
missing_features = [f for f in fraud_model.expected_features if f not in data_train.columns]
if missing_features:
    print(f"\n⚠️  Features manquantes: {missing_features}")
    print("Ajoutez ces colonnes à votre DataFrame:")
    
    # Suggestions pour ajouter les features manquantes
    if 'is_international' not in data_train.columns:
        print("- 'is_international': data_train['is_international'] = (data_train['debtor_country'] != data_train['creditor_country']).astype(int)")
    
    if 'intrbk_sttlm_amt_log' not in data_train.columns:
        print("- 'intrbk_sttlm_amt_log': data_train['intrbk_sttlm_amt_log'] = np.log1p(data_train['intrbk_sttlm_amt'])")
else:
    print("\n✅ Toutes les features nécessaires sont présentes")

Features attendues par le modèle: ['intrbk_sttlm_amt', 'intrbk_sttlm_amt_log', 'is_international']

Features disponibles dans data_train:
['intrbk_sttlm_amt', 'is_international', 'intrbk_sttlm_amt_log']

✅ Toutes les features nécessaires sont présentes